apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-demo
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: demo.my-f5.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  #- name: demo.my-f5.com
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/GSLBServer1
    monitor:
      type: http
      send: "GET / HTTP/1.1\r\nHost: demo.my-f5.com\r\n"
      recv: ""
      interval: 10
      timeout: 10