apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: nginx-ingress-ingresslink
  namespace: nginx-ingress
spec:
  ipamLabel: "Production" # `ipamLabel` option allows the user manage the virtual server address using the F5 IPAM controller.
  selector:
    matchLabels:
      app: nginx-ingress
