apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: my-transport-server
  namespace: nginx-ingress
spec:
  virtualServerAddress: "172.16.3.9"
  virtualServerPort: 443
  virtualServerName: my-ts
  mode: standard
  snat: auto
  pool:
    service: nginx-ingress-tls
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10