apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    cis.f5.com/as3-tenant: nginx-ingress
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: ingresstls_pool
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
      app: nginx-ingress
